### ISSUE TITLE
TraefikFileProviderProxy throws configuration error with default configuration provided in docs: KeyError: 'jupyter'

### ISSUE THREAD

**Issue by devopswise** [jupyterhub/traefik-proxy#171]
Many thanks for this awesome project :)

### Bug description
JupyterHub is not starting with TraefikFileProviderProxy, using default configurations from documentation.
I couldn't have working setup with TraefikFileProvider & jupyterhub. (traefik v1.7)

#### Expected behaviour
It should start normally, add/deletes routes etc. I should be able to access jupyterhub at localhost:8000/

#### Actual behaviour
it throws following error 
```

[I 2023-03-06 14:18:00.504 JupyterHub app:3094] Not starting proxy
[E 2023-03-06 14:18:00.506 JupyterHub app:3334]
    Traceback (most recent call last):
      File "/home/onur/workspace/wsman/jhub-latest/jupyterhub/app.py", line 3332, in launch_instance_async
        await self.start()
      File "/home/onur/workspace/wsman/jhub-latest/jupyterhub/app.py", line 3098, in start
        await self.proxy.get_all_routes()
      File "/home/onur/workspace/wsman/jhub-latest/traefik-proxy/jupyterhub_traefik_proxy/fileprovider.py", line 273, in get_all_routes
        if router not in self.dynamic_config["jupyter"]["routers"]:
                         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
    KeyError: 'jupyter'


```

### How to reproduce
install jupyterhub (tag 3.1.1) using sources
install latest jupyterhub/traefik-proxy, (I have tested with commit fec2918e9 as well)
use dummyauthenticator & dockerspawner 
I start traefik by myself using following configs provided in docs

here is the exact config files I have used:
rules.toml:
```
# Router configuration for the api service
[http.routers.router-api]
rule = "Host(`localhost`) && PathPrefix(`/api`)"
entryPoints = ["enter_api"]
service = "api@internal"
middlewares = ["auth_api"]

# authenticate the traefik api entrypoint
[http.middlewares.auth_api.basicAuth]
users = [ "api_admin:$apr1$eS/j3kum$q/X2khsIEG/bBGsteP.x./",]
```

traefik.toml
```
debug = true
logLevel = "DEBUG"

# the api entrypoint
[api]
dashboard = true

# websockets protocol
[wss]
protocol = "http"

# the port on localhost where traefik accepts http requests
[entryPoints.web]
address = ":8000"

# the port on localhost where the traefik api and dashboard can be found
[entryPoints.enter_api]
address = ":8099"

# the dynamic configuration directory
# This must match the directory provided in Step 1. above.
[providers.file]
directory = "/var/run/traefik"
watch = true
```

### Your personal set up
Debian/testing, python 3.11
classic jupyterhub development setup

pip freeze

```
aiofiles==22.1.0
aiohttp==3.8.4
aiosignal==1.3.1
aiosqlite==0.18.0
alembic==1.9.4
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
async-generator==1.10
async-timeout==4.0.2
attrs==22.2.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
certifi==2022.12.7
certipy==0.1.3
cffi==1.15.1
charset-normalizer==3.0.1
comm==0.1.2
coverage==7.2.1
cryptography==39.0.1
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
docker==6.0.1
-e git+https://github.com/jupyterhub/dockerspawner.git@65e9a23926608a1becf76012657ad538311f7419#egg=dockerspawner
escapism==1.0.1
executing==1.2.0
fastjsonschema==2.16.3
filelock==3.9.0
fqdn==1.5.1
frozenlist==1.3.3
greenlet==2.0.2
h11==0.14.0
html5lib==1.1
idna==3.4
iniconfig==2.0.0
ipykernel==6.21.2
ipython==8.11.0
ipython-genutils==0.2.0
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.11
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.6.3
jupyter-telemetry==0.1.0
jupyter-ydoc==0.2.2
jupyter_client==8.0.3
jupyter_core==5.2.0
jupyter_server==2.3.0
jupyter_server_fileid==0.8.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.6.1
-e git+https://github.com/jupyterhub/jupyterhub.git@7b2c89d46cf42c37c21eef689574ab915cbb26b9#egg=jupyterhub
jupyterhub-dummyauthenticator==0.3.1
jupyterhub-simplespawner==0.1
-e git+https://github.com/jupyterhub/traefik-proxy.git@fec2918e99f673398be60f89f0f542d7ffd1aeeb#egg=jupyterhub_traefik_proxy
jupyterlab==3.6.1
jupyterlab-pygments==0.2.2
jupyterlab_server==2.19.0
Mako==1.2.4
MarkupSafe==2.1.2
matplotlib-inline==0.1.6
mistune==2.0.5
mock==5.0.1
multidict==6.0.4
nbclassic==0.5.2
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
oauthlib==3.2.2
outcome==1.2.0
packaging==23.0
pamela==1.0.0
pandocfilters==1.5.0
parso==0.8.3
passlib==1.7.4
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==3.0.0
pluggy==1.0.0
prometheus-client==0.16.0
prompt-toolkit==3.0.38
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.14.0
pyOpenSSL==23.0.0
pyrsistent==0.19.3
PySocks==1.7.1
pytest==7.2.1
pytest-asyncio==0.20.3
pytest-cov==4.0.0
python-dateutil==2.8.2
python-json-logger==2.0.7
PyYAML==6.0
pyzmq==25.0.0
requests==2.28.2
requests-mock==1.10.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
ruamel.yaml==0.17.21
selenium==4.8.2
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4
SQLAlchemy==2.0.4
stack-data==0.6.2
terminado==0.17.1
tinycss2==1.2.1
toml==0.10.2
tornado==6.2
traitlets==5.9.0
trio==0.22.0
trio-websocket==0.9.2
typing_extensions==4.5.0
uri-template==1.2.0
urllib3==1.26.14
virtualenv==20.20.0
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.1
wsproto==1.2.0
y-py==0.5.9
yarl==1.8.2
ypy-websocket==0.8.2
```

**Comment by minrk** [comment]
Thanks for testing! This is fixed by #173. Note that the current development version of jupyterhub-traefik-proxy only supports traefik v2, not 1.7.
