### ISSUE TITLE
Failed to connect to 127.0.0.1 port 8099: Connection refused

### ISSUE THREAD

**Issue by jtpio** [jupyterhub/traefik-proxy#94]
After installing Traefik with:

```bash
python3 -m jupyterhub_traefik_proxy.install --output=/usr/local/bin
```

Using the following config:

```python
from jupyterhub.auth import DummyAuthenticator
from jupyterhub.spawner import SimpleLocalProcessSpawner
from jupyterhub_traefik_proxy import TraefikTomlProxy

c = get_config()  # noqa

c.JupyterHub.authenticator_class = DummyAuthenticator
c.JupyterHub.spawner_class = SimpleLocalProcessSpawner
c.JupyterHub.proxy_class = TraefikTomlProxy
c.JupyterHub.allow_named_servers = True
```

And starting JupyterHub with:

```bash
python -m jupyterhub -f jupyterhub_config.py --debug
```

The hub is sometimes unable to reach the Traefik API:

```
[D 2020-02-28 12:41:03.057 JupyterHub proxy:153] Fetching traefik api http://127.0.0.1:8099/api/providers/file
[E 2020-02-28 12:41:03.059 JupyterHub proxy:172] Error checking for traefik static configuration
    Traceback (most recent call last):
      File "/home/jtp/miniconda/envs/jhub-traefik/lib/python3.8/site-packages/jupyterhub_traefik_proxy/proxy.py", line 170, in _check_traefik_static_conf_ready
        resp = await self._traefik_api_request("/api/providers/" + provider)
      File "/home/jtp/miniconda/envs/jhub-traefik/lib/python3.8/site-packages/jupyterhub_traefik_proxy/proxy.py", line 154, in _traefik_api_request
        resp = await AsyncHTTPClient().fetch(
    tornado.curl_httpclient.CurlError: HTTP 599: Failed to connect to 127.0.0.1 port 8099: Connection refused
```

Restarting the hub process fixes it sometimes, which makes it look like some kind of race condition.

More complete example in this gist: https://gist.github.com/jtpio/88d98746ed8577403d4e4497370c6950

**Comment by GeorgianaElena** [comment]
@jtpio, as long as the hub process doesn't end with ["Traefik static configuration not available"](https://github.com/jupyterhub/traefik-proxy/blob/master/jupyterhub_traefik_proxy/proxy.py#L186) this error only means that traefik needs more time to load its static config (traefik.toml in this case) and this is called [here](https://github.com/jupyterhub/traefik-proxy/blob/5420fc4e4355cd4b8e7a30a63b3cdbedd22717cf/jupyterhub_traefik_proxy/toml.py#L133).

We allow up to [30s by default](https://github.com/jupyterhub/traefik-proxy/blob/master/jupyterhub_traefik_proxy/proxy.py#L90)(configurable) for traefik to load its static / dynamic config. During this time, we are pinging traefik to see if it's ready.

Traefik was started by the hub in this case, right?

**Comment by jtpio** [comment]
Yes Traefik was started by the hub in this case (using this config: https://gist.github.com/jtpio/88d98746ed8577403d4e4497370c6950).

Sometimes this message is printed only once and the hub continues as normal. But sometimes this is what happens:

![traefik-connection-refused](https://user-images.githubusercontent.com/591645/75670063-5e89a300-5c7c-11ea-914f-160b9d19edd5.gif)

After the 30s, the hub process terminates.

**Comment by GeorgianaElena** [comment]
I don't seem to be able to reproduce this :( Is the traefik process running when this is happening?

If yes, try setting `TraefikTomlProxy.traefik_api_username` and `TraefikTomlProxy.traefik_api_password` and then login with these credentials into traefik's dashboard (on port 8099) when the errors pop. If the dashboard is accessible then it means traefik is working ok and it might be something wrong with the communication between the hub and traefik.

**Comment by jtpio** [comment]
It appears to be running:

![traefik-jhub-process](https://user-images.githubusercontent.com/591645/75693255-f9977280-5ca6-11ea-9b2a-0d147ae390fd.gif)

I'll check with an explicit config (username and password). But it looks like they are generated if not specified?

https://github.com/jupyterhub/traefik-proxy/blob/a968d813f4388657c0a1d36c09fd84d0d43ac779/jupyterhub_traefik_proxy/proxy.py#L74-L103

**Comment by jtpio** [comment]
Using this config:

```python
import os

from jupyterhub.auth import DummyAuthenticator
from jupyterhub.spawner import SimpleLocalProcessSpawner
from jupyterhub_traefik_proxy import TraefikTomlProxy

c = get_config()  # noqa

c.JupyterHub.authenticator_class = DummyAuthenticator
c.JupyterHub.spawner_class = SimpleLocalProcessSpawner
c.JupyterHub.proxy_class = TraefikTomlProxy
c.JupyterHub.allow_named_servers = True

c.TraefikTomlProxy.traefik_api_username='hub'
c.TraefikTomlProxy.traefik_api_password='hub'
```

`rules.toml`and `traefik.toml` are generated in the current working directory with the following content:

```
$ cat traefik.toml
defaultentrypoints = [ "http",]
debug = true
logLevel = "ERROR"

[api]
dashboard = true
entrypoint = "auth_api"

[wss]
protocol = "http"

[file]
filename = "rules.toml"
watch = true

[entryPoints.http]
address = ":8000"

[entryPoints.auth_api]
address = ":8099"

[entryPoints.auth_api.auth.basic]
users = [ "hub:$apr1$hsgg9D/Q$X9EYYofZhk5e7ASFkhjOW1",]
```

```
[frontends.frontend__2F]
backend = "backend__2F"
passHostHeader = true

[backends.backend__2F.servers.server1]
url = "http://127.0.0.1:8081"
weight = 1

[frontends.frontend__2F.routes.test]
rule = "PathPrefix:/"
data = "{\"hub\": true}"
```

It really seems to be random. Most of the time the hub would start, print `Failed to connect to 127.0.0.1 port 8099: Connection refused` and continue normally.

**Comment by GeorgianaElena** [comment]
> I'll check with an explicit config (username and password). But it looks like they are generated if not specified?

Yup, those are generated but I don't believe you can find out what's the password that got generated. With your own configured username and password, you can login into traefik's dashboard:
![traefik-dashboard](https://user-images.githubusercontent.com/7579677/75771717-3620a800-5d53-11ea-8174-aeabf16b0ba8.gif)

Also, what changed in the last gif (the one that shows that traefik proc is running)? It seems the error is 401 and not 599 like in the previous one.

**Comment by jtpio** [comment]
Thanks @GeorgianaElena for checking!

Yes I get that one too, and in that case the auth works well.

The 599 happens after several restarts (which maybe stops the hub too fast).

**Comment by manics** [comment]
Does this occur with the current dev version (install from `main`) which has recently had a big refactoring to work with Traefik v2?

**Comment by Erikhksquad** [comment]
Ok
